version: '3.8'

# Services
services:

    # PHP Service
    php:
        build:
            dockerfile: php-dockerfile
        volumes:
            - './php-files:/var/www/html' # This line maps your local php-files directory to the virtual /var/www/html directory in the docker container (rename php-files directory locally and here to be whatever you want them to be)
        depends_on:
            - db

    # Nginx Service
    nginx:
        image: nginx:alpine
        ports:
            - 80:80
        links:
            - 'php'
        volumes:
            - './php-files:/var/www/html' # This is another reference to line 11 so if you rename php-files directory to something else, you should also update it here
            - './conf.d:/etc/nginx/conf.d'
        depends_on:
            - php

    # MySQL Service
    db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'crafting-app'
            MYSQL_USER: 'darcy'
            MYSQL_PASSWORD: 'password'
        volumes:
            - ./mysql_data:/var/lib/mysql # This line maps your local mysql_data directory to the virtual /var/lib/mysql directory in the docker container (rename mysql_data directory locally and here to whatever you want them to be)
